/// <reference types="vite/client" />

declare module '*.svg' {
  const content: string;
  export default content;
}

declare module '*.png' {
  const content: string;
  export default content;
}

declare module '*.css' {
  const content: Record<string, string>;
  export default content;
}

// Virtual module generated by vite-plugin-templates
declare module 'virtual:bundled-templates' {
  /**
   * Auto-generated list of bundled template filenames.
   * Discovered at build time from public/templates/*.guido.json
   */
  export const BUNDLED_TEMPLATES: string[];
}
